import type {Metadata} from 'next'
import {poppins} from '@/components/ui/font'
import './globals.css'

export const metadata: Metadata = {
  title: 'Nitro Mart',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-display`}>{children}</body>
    </html>
  )
}
