import type { Metadata } from "next";
import { displayFont, textFont } from "@/components/ui/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "binaryryde",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${displayFont.variable} ${textFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
